[package]
name = "fwlr-io"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
leptos = { version = "0.8.20", features = ["nightly", "csr"] }
leptos_router = { version = "0.8.14", features = ["nightly"] }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1

[package.metadata.leptos]
assets-dir = "public"
